### ISSUE TITLE
So how can I use this?

### ISSUE THREAD

**Issue by AddictedPotato** [HermesTheDev/sploit#1]
I'm pretty sure I know what this does but how do I use it?

**Comment by ajbuchholz** [comment]
1. Click the Download Button
2. Download the Zip and Unzip 
3. Open your Mac Terminal
4. Use the “cd” command to access the folder. If the unzipped file is in Downloads do “cd Downloads/folder name”
5. Then “make run”
6. If it works properly an admin terminal should appear. From there escalate yourself to admin. You can google this.

**Comment by AddictedPotato** [comment]
Awesome, thanks for the help. Can the admin see that I'm doing this?

**Comment by ajbuchholz** [comment]
Probably. But you most likely won’t get in trouble.

**Comment by AddictedPotato** [comment]
Sadly I think this is outdated because it says "Agreeing to the Xcode/IOS license requires admin privileges" when I used "make run"

**Comment by ajbuchholz** [comment]
What version of macOS are you running? This works on versions up to 10.14.3

**Comment by AddictedPotato** [comment]
I'm on 10.14.3

**Comment by ajbuchholz** [comment]
Hmm. I honestly have no idea. Can you send me the terminal errors or whatever you are getting?

**Comment by AddictedPotato** [comment]
Here's my errors, thx again for the help

![Screen Shot 2](https://user-images.githubusercontent.com/76059603/102376428-9f477400-3f91-11eb-9744-252f30b46828.png)

**Comment by ajbuchholz** [comment]
Still works for me. I just confirmed on 10.14.3 | Mojave. Your “cd” command should be 
“cd Downloads/sploit-master 2”
“make run” 

also should mention the terminal may open but not appear. If that happens click the terminal icon in the lower right of the dock and click Shell > New Window

**Comment by AddictedPotato** [comment]
Yeah, I changed my code to cd "Downloads/sploit-master 2" and it still gave me the XCode error. Odd. I opened a new window of the terminal and it looked the same. Will it look different if I do it right? 

Anyway I still tried to escalate myself to admin and now it says this incident will be reported. I guess I'm wanted by the FBI now, lol

**Comment by ajbuchholz** [comment]
Nah. Don’t worry about it being reported. I suspect the issue lies within your version... can you send me a screenshot of your macOS version? If not I have one more idea. 
1. open new terminal
2. `git clone https://github.com/hermesthedev/sploit`
3. `cd sploit`
4. `make run`

**you will need to install developer tools. This should be installed when you do the git command.** 
Otherwise I have no idea.

**Comment by AddictedPotato** [comment]
So I've done some research and it turns out that It's a entirely different problem. I appreciate the information you've supplied me with but sadly, I probably won't be able to do this any time soon.

**Comment by AddictedPotato** [comment]
Since for some reason I have Xcode installed, I need to accept the TOS before I can continue. Unfortunately I need admin access to accept it and I'm not an admin.
